[package]
name = "network-initializer"
version = "0.1.0"
edition = "2021"

[dependencies]
wg_2024 = { git = "https://github.com/WGL-2024/WGL_repo_2024.git", features = ["serialize"] }
simulation-controller = { git = "https://github.com/Rustbusters/simulation-controller.git", branch = "dev/common" }
#simulation-controller = { path = "../simulation-controller" }
node = { git = "https://github.com/Rustbusters/node.git", branch = "dev/common" }
#node = { path = "../node" }
#client = { git = "https://github.com/Rustbusters/client.git" }
client = { path = "../client", features = ["embedded_assets"] }
rustbusters-drone = { git = "https://github.com/Rustbusters/drone.git" }
#rustbusters-drone = { path = "../rustbusters-drone" }
common-utils = { git = "https://github.com/Rustbusters/common-utils.git" }
#common-utils = { path = "../common-utils" }
crossbeam-channel = "0.5.13"
toml = "0.8.19"
env_logger = "0.9"
log = "0.4"
rand = "0.8.5"