[package]
name = "network-initializer"
version = "0.1.0"
edition = "2021"

[dependencies]
wg_2024 = { git = "http://github.com/WGL-2024/WGL_repo_2024.git", features = ["serialize"] }
node = { git = "ssh://github.com/Rustbusters/node.git" }
drone = { git = "ssh://github.com/Rustbusters/drone.git" }
crossbeam-channel = "0.5.13"
toml = "0.8.19"