[[drone]]
id = 1
connected_node_ids = [2, 101]
pdr = 0.05

[[drone]]
id = 2
connected_node_ids = [1, 4, 6, 9]
pdr = 0.05

[[drone]]
id = 3
connected_node_ids = [10, 200]
pdr = 0.05

[[drone]]
id = 4
connected_node_ids = [2, 5, 10, 200]
pdr = 0.05

[[drone]]
id = 5
connected_node_ids = [4, 6, 201]
pdr = 0.05

[[drone]]
id = 6
connected_node_ids = [2, 5, 7, 10, 100, 102]
pdr = 0.05

[[drone]]
id = 7
connected_node_ids = [6, 8, 9]
pdr = 0.05

[[drone]]
id = 8
connected_node_ids = [7, 100]
pdr = 0.05

[[drone]]
id = 9
connected_node_ids = [2, 7, 200, 201]
pdr = 0.05

[[drone]]
id = 10
connected_node_ids = [3, 4, 6, 101]
pdr = 0.05

[[client]]
id = 100
connected_drone_ids = [6, 8]

[[client]]
id = 101
connected_drone_ids = [1, 10]

[[client]]
id = 102
connected_drone_ids = [6]

[[server]]
id = 200
connected_drone_ids = [3, 4, 9]

[[server]]
id = 201
connected_drone_ids = [5, 9, 2]