name: Sync UI folder to react-sc

on:
  push:
    branches:
      - main
    paths:
      - 'static/**'

jobs:
  sync-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout della prima repo (network-initializer)
        uses: actions/checkout@v4

      - name: Clona la seconda repo (react-sc)
        run: |
          git clone https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/Rustbusters/react-sc.git react-sc

      - name: Copia la cartella aggiornata
        run: |
          rsync -av --delete static/ react-sc/tauri-src/static/

      - name: Commit e push
        run: |
          cd react-sc
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Automatic UI sync with GitHub Actions" || exit 0
          git push
